name: HTML Validator
on: [push, pull_request]

jobs:
  html5validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Validator
        run: pip install html5validator
      - name: Run Validation
        run: html5validator --root . --ignore-re "node_modules"
