name: SAI Roots Web Optimizer

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  optimize_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. GENERATE SITEMAP (Otomatis 28 Lagu)
      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://sairootmusic.com/
          drop-html-extension: true
          additional-explicit-url: |
            https://sairootmusic.com/music?song=drama-klenik
            https://sairootmusic.com/music?song=senandung-manis
            https://sairootmusic.com/music?song=eksploitasi
            https://sairootmusic.com/music?song=jurus-liar
            https://sairootmusic.com/music?song=dari-jauh
            https://sairootmusic.com/music?song=kasih-mengalun
            https://sairootmusic.com/music?song=genjer-hijau
            https://sairootmusic.com/music?song=timpang
            https://sairootmusic.com/music?song=babylon-burn
            https://sairootmusic.com/music?song=bayang-singgasana
            https://sairootmusic.com/music?song=blaze-it-up
            https://sairootmusic.com/music?song=evaluasi-lagi
            https://sairootmusic.com/music?song=irama-hidup
            https://sairootmusic.com/music?song=jamaican-sound
            https://sairootmusic.com/music?song=ormas-tipu-tipu
            https://sairootmusic.com/music?song=propaganda
            https://sairootmusic.com/music?song=roots-medication
            https://sairootmusic.com/music?song=skank-patrol
            https://sairootmusic.com/music?song=reborn-riddim
            https://sairootmusic.com/music?song=autopsi-mic
            https://sairootmusic.com/music?song=salam-dari-timur
            https://sairootmusic.com/music?song=mantra-malam
            https://sairootmusic.com/music?song=magic-mushroom
            https://sairootmusic.com/music?song=rastaman
            https://sairootmusic.com/music?song=melayang-pelan
            https://sairootmusic.com/music?song=tanah-hijau
            https://sairootmusic.com/music?song=bbm-busuk
            https://sairootmusic.com/music?song=kabur-saja-dulu

      # 2. HTML VALIDATOR (Hanya peringatan, tidak bikin STOP kalau gagal)
      - name: HTML Validator
        uses: Cypherous/html5validator-action@v1
        continue-on-error: true # Biar tetep lanjut meski ada salah tulis kode
        with:
          root: .

      # 3. COMMIT SEMUA PERUBAHAN
      - name: Commit and Push
        run: |
          git config --global user.name 'SAI Roots Bot'
          git config --global user.email 'bot@sairootmusic.com'
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update: Sitemap & Optimization" && git push)
