name: Generate XML Sitemap

on:
  push:
    branches:
      - main

# Tambahkan izin ini agar bot bisa nge-push sitemap.xml
permissions:
  contents: write

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://sairootmusic.com/
        drop-html-extension: true

    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml
        # Cek jika ada perubahan, baru commit
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Automated sitemap update"
          git push
        else
          echo "No changes to commit"
        fi
