name: Generate XML Sitemap

on:
  push:
    branches:
      - main # Atau sesuaikan dengan nama branch utama Anda (misal: master)

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://sairootmusic.com/
        # Menghapus ekstensi .html dari URL di sitemap
        drop-html-extension: true
        # Memastikan index tidak muncul sebagai /index tapi sebagai /
        include-pdf: false

    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automated sitemap update" && git push)
